modLoader="javafml"
loaderVersion="[37,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/Zuxelus/Energy-Control/issues"

[[mods]]
modId="energycontrol"
version="${file.jarVersion}"
displayName="Energy Control"
displayURL="https://www.curseforge.com/minecraft/mc-mods/energy-control"
logoFile="logo.png"
credits="Remastered by Zuxelus, originally created by Shedar, based on an original idea by Nargon and Noosius"
authors="Zuxelus"
description='''
Energy Control is a remastered version of original Nuclear Control, an Industrial Craft 2 addon that allows you to build efficient monitoring and notification system for your energy flow.
'''

[[dependencies.energycontrol]]
    modId="forge"
    mandatory=true
    versionRange="[37.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.energycontrol]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="AFTER"
    side="BOTH"